// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/marketdata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Indicators    *IndicatorConfig       `protobuf:"bytes,2,opt,name=indicators,proto3" json:"indicators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_marketdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_marketdata_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StreamRequest) GetIndicators() *IndicatorConfig {
	if x != nil {
		return x.Indicators
	}
	return nil
}

type IndicatorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RsiPeriod     int32                  `protobuf:"varint,1,opt,name=rsi_period,json=rsiPeriod,proto3" json:"rsi_period,omitempty"`
	SmaPeriod     int32                  `protobuf:"varint,2,opt,name=sma_period,json=smaPeriod,proto3" json:"sma_period,omitempty"`
	EmaPeriod     int32                  `protobuf:"varint,3,opt,name=ema_period,json=emaPeriod,proto3" json:"ema_period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndicatorConfig) Reset() {
	*x = IndicatorConfig{}
	mi := &file_proto_marketdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndicatorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicatorConfig) ProtoMessage() {}

func (x *IndicatorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicatorConfig.ProtoReflect.Descriptor instead.
func (*IndicatorConfig) Descriptor() ([]byte, []int) {
	return file_proto_marketdata_proto_rawDescGZIP(), []int{1}
}

func (x *IndicatorConfig) GetRsiPeriod() int32 {
	if x != nil {
		return x.RsiPeriod
	}
	return 0
}

func (x *IndicatorConfig) GetSmaPeriod() int32 {
	if x != nil {
		return x.SmaPeriod
	}
	return 0
}

func (x *IndicatorConfig) GetEmaPeriod() int32 {
	if x != nil {
		return x.EmaPeriod
	}
	return 0
}

type MarketUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*MarketUpdate_Price
	//	*MarketUpdate_Indicators
	Update        isMarketUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketUpdate) Reset() {
	*x = MarketUpdate{}
	mi := &file_proto_marketdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketUpdate) ProtoMessage() {}

func (x *MarketUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketUpdate.ProtoReflect.Descriptor instead.
func (*MarketUpdate) Descriptor() ([]byte, []int) {
	return file_proto_marketdata_proto_rawDescGZIP(), []int{2}
}

func (x *MarketUpdate) GetUpdate() isMarketUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *MarketUpdate) GetPrice() *PriceUpdate {
	if x != nil {
		if x, ok := x.Update.(*MarketUpdate_Price); ok {
			return x.Price
		}
	}
	return nil
}

func (x *MarketUpdate) GetIndicators() *IndicatorUpdate {
	if x != nil {
		if x, ok := x.Update.(*MarketUpdate_Indicators); ok {
			return x.Indicators
		}
	}
	return nil
}

type isMarketUpdate_Update interface {
	isMarketUpdate_Update()
}

type MarketUpdate_Price struct {
	Price *PriceUpdate `protobuf:"bytes,1,opt,name=price,proto3,oneof"`
}

type MarketUpdate_Indicators struct {
	Indicators *IndicatorUpdate `protobuf:"bytes,2,opt,name=indicators,proto3,oneof"`
}

func (*MarketUpdate_Price) isMarketUpdate_Update() {}

func (*MarketUpdate_Indicators) isMarketUpdate_Update() {}

type PriceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Volume        float64                `protobuf:"fixed64,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceUpdate) Reset() {
	*x = PriceUpdate{}
	mi := &file_proto_marketdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceUpdate) ProtoMessage() {}

func (x *PriceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceUpdate.ProtoReflect.Descriptor instead.
func (*PriceUpdate) Descriptor() ([]byte, []int) {
	return file_proto_marketdata_proto_rawDescGZIP(), []int{3}
}

func (x *PriceUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceUpdate) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PriceUpdate) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *PriceUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type IndicatorUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rsi           float64                `protobuf:"fixed64,1,opt,name=rsi,proto3" json:"rsi,omitempty"`
	Sma           float64                `protobuf:"fixed64,2,opt,name=sma,proto3" json:"sma,omitempty"`
	Ema           float64                `protobuf:"fixed64,3,opt,name=ema,proto3" json:"ema,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RsiHistory    []float64              `protobuf:"fixed64,5,rep,packed,name=rsi_history,json=rsiHistory,proto3" json:"rsi_history,omitempty"`
	SmaHistory    []float64              `protobuf:"fixed64,6,rep,packed,name=sma_history,json=smaHistory,proto3" json:"sma_history,omitempty"`
	EmaHistory    []float64              `protobuf:"fixed64,7,rep,packed,name=ema_history,json=emaHistory,proto3" json:"ema_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndicatorUpdate) Reset() {
	*x = IndicatorUpdate{}
	mi := &file_proto_marketdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndicatorUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicatorUpdate) ProtoMessage() {}

func (x *IndicatorUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_marketdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicatorUpdate.ProtoReflect.Descriptor instead.
func (*IndicatorUpdate) Descriptor() ([]byte, []int) {
	return file_proto_marketdata_proto_rawDescGZIP(), []int{4}
}

func (x *IndicatorUpdate) GetRsi() float64 {
	if x != nil {
		return x.Rsi
	}
	return 0
}

func (x *IndicatorUpdate) GetSma() float64 {
	if x != nil {
		return x.Sma
	}
	return 0
}

func (x *IndicatorUpdate) GetEma() float64 {
	if x != nil {
		return x.Ema
	}
	return 0
}

func (x *IndicatorUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *IndicatorUpdate) GetRsiHistory() []float64 {
	if x != nil {
		return x.RsiHistory
	}
	return nil
}

func (x *IndicatorUpdate) GetSmaHistory() []float64 {
	if x != nil {
		return x.SmaHistory
	}
	return nil
}

func (x *IndicatorUpdate) GetEmaHistory() []float64 {
	if x != nil {
		return x.EmaHistory
	}
	return nil
}

var File_proto_marketdata_proto protoreflect.FileDescriptor

const file_proto_marketdata_proto_rawDesc = "" +
	"\n" +
	"\x16proto/marketdata.proto\x12\n" +
	"marketdata\"d\n" +
	"\rStreamRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12;\n" +
	"\n" +
	"indicators\x18\x02 \x01(\v2\x1b.marketdata.IndicatorConfigR\n" +
	"indicators\"n\n" +
	"\x0fIndicatorConfig\x12\x1d\n" +
	"\n" +
	"rsi_period\x18\x01 \x01(\x05R\trsiPeriod\x12\x1d\n" +
	"\n" +
	"sma_period\x18\x02 \x01(\x05R\tsmaPeriod\x12\x1d\n" +
	"\n" +
	"ema_period\x18\x03 \x01(\x05R\temaPeriod\"\x88\x01\n" +
	"\fMarketUpdate\x12/\n" +
	"\x05price\x18\x01 \x01(\v2\x17.marketdata.PriceUpdateH\x00R\x05price\x12=\n" +
	"\n" +
	"indicators\x18\x02 \x01(\v2\x1b.marketdata.IndicatorUpdateH\x00R\n" +
	"indicatorsB\b\n" +
	"\x06update\"q\n" +
	"\vPriceUpdate\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x01R\x06volume\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xc8\x01\n" +
	"\x0fIndicatorUpdate\x12\x10\n" +
	"\x03rsi\x18\x01 \x01(\x01R\x03rsi\x12\x10\n" +
	"\x03sma\x18\x02 \x01(\x01R\x03sma\x12\x10\n" +
	"\x03ema\x18\x03 \x01(\x01R\x03ema\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vrsi_history\x18\x05 \x03(\x01R\n" +
	"rsiHistory\x12\x1f\n" +
	"\vsma_history\x18\x06 \x03(\x01R\n" +
	"smaHistory\x12\x1f\n" +
	"\vema_history\x18\a \x03(\x01R\n" +
	"emaHistory2Z\n" +
	"\x11MarketDataService\x12E\n" +
	"\fStreamPrices\x12\x19.marketdata.StreamRequest\x1a\x18.marketdata.MarketUpdate0\x01B*Z(github.com/yourusername/quantacode/protob\x06proto3"

var (
	file_proto_marketdata_proto_rawDescOnce sync.Once
	file_proto_marketdata_proto_rawDescData []byte
)

func file_proto_marketdata_proto_rawDescGZIP() []byte {
	file_proto_marketdata_proto_rawDescOnce.Do(func() {
		file_proto_marketdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_marketdata_proto_rawDesc), len(file_proto_marketdata_proto_rawDesc)))
	})
	return file_proto_marketdata_proto_rawDescData
}

var file_proto_marketdata_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_marketdata_proto_goTypes = []any{
	(*StreamRequest)(nil),   // 0: marketdata.StreamRequest
	(*IndicatorConfig)(nil), // 1: marketdata.IndicatorConfig
	(*MarketUpdate)(nil),    // 2: marketdata.MarketUpdate
	(*PriceUpdate)(nil),     // 3: marketdata.PriceUpdate
	(*IndicatorUpdate)(nil), // 4: marketdata.IndicatorUpdate
}
var file_proto_marketdata_proto_depIdxs = []int32{
	1, // 0: marketdata.StreamRequest.indicators:type_name -> marketdata.IndicatorConfig
	3, // 1: marketdata.MarketUpdate.price:type_name -> marketdata.PriceUpdate
	4, // 2: marketdata.MarketUpdate.indicators:type_name -> marketdata.IndicatorUpdate
	0, // 3: marketdata.MarketDataService.StreamPrices:input_type -> marketdata.StreamRequest
	2, // 4: marketdata.MarketDataService.StreamPrices:output_type -> marketdata.MarketUpdate
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_marketdata_proto_init() }
func file_proto_marketdata_proto_init() {
	if File_proto_marketdata_proto != nil {
		return
	}
	file_proto_marketdata_proto_msgTypes[2].OneofWrappers = []any{
		(*MarketUpdate_Price)(nil),
		(*MarketUpdate_Indicators)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_marketdata_proto_rawDesc), len(file_proto_marketdata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_marketdata_proto_goTypes,
		DependencyIndexes: file_proto_marketdata_proto_depIdxs,
		MessageInfos:      file_proto_marketdata_proto_msgTypes,
	}.Build()
	File_proto_marketdata_proto = out.File
	file_proto_marketdata_proto_goTypes = nil
	file_proto_marketdata_proto_depIdxs = nil
}
